version: '3.5'

services:

  bahmni:
    build:
      context: bahmni
      dockerfile: Dockerfile
      args:
        - BAHMNI_IMPL_NAME=${bahmni_implementation_name}
        - BAHMNI_TIMEZONE=${bahmni_timezone}
        - BAHMNI_INSTALLER_URL=${bahmni_installer_url}
        - BAHMNI_IMPLEMENTATION_REPO=${bahmni_implementation_repo}
        - BAHMNI_IMPLEMENTATION_BRANCH=${bahmni_implementation_branch}
        - BAHMNI_OPENELIS_ENABLED=$bahmni_openelis_enabled
        - BAHMNI_REPORTS_ENABLED=$bahmni_reports_enabled
        - BAHMNI_OPENMRS_USERNAME=${bahmni_openmrs_username}
        - BAHMNI_OPENMRS_PASSWORD=${bahmni_openmrs_password}
        - BAHMNI_OPENELIS_USERNAME=${bahmni_openelis_username}
        - BAHMNI_OPENELIS_PASSWORD=${bahmni_openelis_password}
        - BAHMNI_REPORTS_USERNAME=${bahmni_reports_username}
        - BAHMNI_REPORTS_PASSWORD=${bahmni_reports_password}
