version: "3.3"

services:

  bahmni-uat:
    image: localhost:5000/${image_name}:${image_version_uat}
    hostname: ${hostname}-uat
    container_name: ${hostname}-uat-container
    tmpfs: /tmp
    environment:
      - BAHMNI_IMPL_NAME=${bahmni_implementation_name}
      - BAHMNI_SERVER_MODE=active
      - BAHMNI_SETUP_REPLICATION=no
      - BAHMNI_POSTGRES_PRESENT=$bahmni_postgres_present
      - BAHMNI_REPLICATION_USERNAME=$bahmni_replication_username
      - BAHMNI_REPLICATION_PASSWORD=$bahmni_replication_password
      - BAHMNI_ACTIVE_HOST=localhost
      - BAHMNI_PASSIVE_HOST=
      - BAHMNI_ENC_FILE_PATH=$bahmni_enc_file_path
      - BAHMNI_BACKUP_PASSIVE=no
      - BAHMNI_BACKUP_NESTOR=no
      - BAHMNI_NESTOR_BACKUP_DIR=$nestor_backup_dir
    command: "bash -e /start.sh active no"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: bahmni_uat_mysql_data
        target: /var/lib/mysql
      - type: volume
        source: bahmni_uat_pgsql_data
        target: /var/lib/pgsql
      - type: bind
        source: ${bahmni_enc_host_path}
        target: ${bahmni_enc_file_path}

volumes:
  bahmni_uat_mysql_data:
  bahmni_uat_pgsql_data:

